apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-mistral
  ports:
  - name: http-metrics
    port: 8000
    targetPort: 8000
    nodePort: 30007
